name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: DockerBuild
      run: docker build -t getting-started .
      
    - name: DockerStart
      run: docker run -dp 8080:8080 getting-started

    - name: TestMain
      run: go test -v ./iproto_server_test.go
